image: maven:3.6.3-openjdk-8
stages:
  - scanner

example-sonar:
  stage: scanner
  script:
    - mvn clean verify -Dmaven.test.skip=true
    - mvn -e -X --batch-mode sonar:sonar
      -Dsonar.host.url=http://127.0.0.1:9000
      -Dsonar.login=admin
      -Dsonar.password=admin
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      -Dsonar.issuesReport.html.enable=true
      -Dsonar.preview.excludePlugins=issueassign,scmstats